In [1]:
import numpy as np
print(np.__version__)

1.26.0


In [2]:
import pandas as pd

In [19]:
#CONVERT LISTS INTO NUMPY ARRAYS
l = [[1,2,3,4,5,6],[4,8,3,0,1,5]]
n = np.array(l)
print(n)

[[1 2 3 4 5 6]
 [4 8 3 0 1 5]]


In [23]:
#CHECKING PROPERTIES OF OUR ARRAY(n)
print(n.ndim) #Shows Dimensionality of our Array(n) --> 1D, 2D, 3D ...ETC
print(n.shape) #Shows Shape of Array --> number of rows and cols
print(n.size) #Shows the size of Array --> number of total elements in Array
print(n.dtype) #Shows the datatype of element holded inside Array --> int32,int64,float32,float64 ETC

2
(2, 6)
12
int32


In [22]:
#Scalar Addtion to matrix --> We dont have to loop through each element in Numpy Arrays
n=n+1
n

array([[2, 3, 4, 5, 6, 7],
       [5, 9, 4, 1, 2, 6]])

In [28]:
#Scalar Multiplication
n = n*2
n

array([[ 4,  6,  8, 10, 12, 14],
       [10, 18,  8,  2,  4, 12]])

In [29]:
#Scalar Subtraction
n = n-2
n

array([[ 2,  4,  6,  8, 10, 12],
       [ 8, 16,  6,  0,  2, 10]])

In [30]:
#Scalar Dvision
n = n/2
n

array([[1., 2., 3., 4., 5., 6.],
       [4., 8., 3., 0., 1., 5.]])

In [26]:
#Perform Transpose of a Matrix (Array)
transpose = n.T
print(transpose.shape)
print(transpose)

(6, 2)
[[2 5]
 [3 9]
 [4 4]
 [5 1]
 [6 2]
 [7 6]]


In [27]:
#Array Creation methods - Using np.ones()
#It creates array containing only 1s by passing number of rows, cols as tuple in arguments
rows,cols = 2,3
ones = np.ones((rows,cols),dtype='int32')
print(ones)

[[1 1 1]
 [1 1 1]]


In [33]:
zeros = np.zeros((rows,cols), dtype='float32')
zeros

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [37]:
arange = np.arange(2,9,2)
arange

array([2, 4, 6, 8])

In [40]:
linspace = np.linspace(2,9,7)
linspace

array([2.        , 3.16666667, 4.33333333, 5.5       , 6.66666667,
       7.83333333, 9.        ])

In [41]:
print(zeros.reshape(6,1))

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [58]:
#random number generation

rng = np.random.default_rng(1445)
random_arr =rng.random(10)
print(random_arr)
print(random_arr[1])

[0.17571157 0.99950176 0.41278619 0.00398696 0.11176873 0.99486958
 0.87620824 0.40839559 0.83600765 0.97905791]
0.9995017644987799


In [61]:
rng = np.random.default_rng(123)
normal = rng.normal(3,10,6)
print(normal)

[-6.8912135  -0.67786651 15.87925261  4.93974419 12.202309    8.77103791]


In [62]:
rng = np.random.default_rng(99)
integer = rng.integers(0,10,8)
print(integer)

[9 5 7 5 1 5 9 9]


In [68]:
#INDEXING & SLICING

print(integer[1])
print(integer[1:])
print(integer[1:5])
print(integer[:6])
print(integer[1::2])

5
[5 7 5 1 5 9 9]
[5 7 5 1]
[9 5 7 5 1 5]
[5 5 5 9]


In [78]:
#Filtering data
filtered_array = integer[integer>=7]
print(filtered_array)

filtered_array2 = integer[integer!=7]
print(filtered_array2)

mask1 = ((integer>=6) & (integer<9))
filtered_array3 = integer[mask]
print(filtered_array3)

mask1 = ((integer==6) | (integer==9))
filtered_array4 = integer[mask]
print(filtered_array4)

[9 7 9 9]
[9 5 5 1 5 9 9]
[7]
[9 9 9]


In [82]:
#Numpy .where()

print(integer)
np.where(integer<7,"Yes","No")

[9 5 7 5 1 5 9 9]


array(['No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No'], dtype='<U3')

In [89]:
#Aggregation methodas - min, max, sum, stddev, mean

print(integer.sum())
print(integer.mean())
print(integer.std())
print(integer.min())
print(integer.max())

50
6.25
2.6339134382131846
1
9


In [93]:
##Aggregation across rows (for rows--> axis=0, for cols--> axis=1)
l1= [[1,7,3,0,3],[6,8,2,0,3]]
l1 = np.array(l1)
print(l1.max(axis=0))
print(l1.max(axis=1))

print(l1.mean(axis=0))
print(l1.mean(axis=1))

[6 8 3 0 3]
[7 8]
[3.5 7.5 2.5 0.  3. ]
[2.8 3.8]


In [97]:
#np.unique() method --> Return Unique element from array
l1= [1,1,3,7,3,4,0,5]
print(np.unique(l1))

[0 1 3 4 5 7]


In [98]:
#np.sqrt() --> return sqrt for each elements in array
print(np.sqrt(l1))

[1.         1.         1.73205081 2.64575131 1.73205081 2.
 0.         2.23606798]


In [102]:
#Sorting arrays
l1= [1,1,3,7,3,4,0,5]
print(l1)
l1.sort()
print(l1)

[1, 1, 3, 7, 3, 4, 0, 5]
[0, 1, 1, 3, 3, 4, 5, 7]


In [7]:
#Sorting arrays across rows(axis=0) & cols(axis=1)
l1= [[1,7,3,0,3],[0,8,2,0,3]]
l1 = np.array(l1)
print(l1)
l1 =l1.T
l1.sort()
l1 = l1.T
print(l1)

'''
print(l1)
np.sort(l1,axis=0)
print(l1)'''

[[1 7 3 0 3]
 [0 8 2 0 3]]
[[0 7 2 0 3]
 [1 8 3 0 3]]


'\nprint(l1)\nnp.sort(l1,axis=0)\nprint(l1)'

In [3]:
print(pd.__version__)

2.2.2


In [23]:
#Making a Series of data from List --> A series is nothing but collection of data in column fashion mapped with index values
sales = [10,20,30,40,50,60]
sales_series = pd.Series(sales,name='sales_column')
sales_series

0    10
1    20
2    30
3    40
4    50
5    60
Name: sales_column, dtype: int64

In [24]:
#Properties of series--> values, index, name, dtype
print(sales_series.values)
print(sales_series.index)
print(sales_series.name)
print(sales_series.dtype)

[10 20 30 40 50 60]
RangeIndex(start=0, stop=6, step=1)
sales_column
int64


In [30]:
#Change datatype of a series
sales_series = sales_series.astype('float32')
sales_series

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
5    60.0
Name: sales_column, dtype: float32

In [34]:
#Indexing & Slicing of series
print(sales_series[0], end='\n\n')
print(sales_series[2:],end='\n\n')
print(sales_series[::2], end='')

10.0

2    30.0
3    40.0
4    50.0
5    60.0
Name: sales_column, dtype: float32

0    10.0
2    30.0
4    50.0
Name: sales_column, dtype: float32

In [38]:
#Making custom index
item = ['coffee','tea','sugar','milk','water','milk_powder']
sales = [10,20,30,40,50,60]
sales_series = pd.Series(sales, index=item, name='sales')

coffee         10
tea            20
sugar          30
milk           40
water          50
milk_powder    60
Name: sales, dtype: int64

20

tea      20
sugar    30
milk     40
water    50
Name: sales, dtype: int64


In [39]:
#Indexing & slicing on custom indexes
print(sales_series,end='\n\n')
print(sales_series['tea'],end='\n\n')
print(sales_series['tea':'water'])

coffee         10
tea            20
sugar          30
milk           40
water          50
milk_powder    60
Name: sales, dtype: int64

20

tea      20
sugar    30
milk     40
water    50
Name: sales, dtype: int64


In [7]:
#Reset index --> back to numerical indexing from custom index --> its a way to handle duplicate values in custom index 
item = ['coffee','coffee','sugar','milk','water','milk_powder']
sales = [10,20,30,40,50,60]
sales_series = pd.Series(sales, index=item, name='sales')
print(sales_series,end='\n\n')

sales_series=sales_series.reset_index()
print(sales_series)

coffee         10
coffee         20
sugar          30
milk           40
water          50
milk_powder    60
Name: sales, dtype: int64

         index  sales
0       coffee     10
1       coffee     20
2        sugar     30
3         milk     40
4        water     50
5  milk_powder     60


In [15]:
#Sorting a series by column name
print(sales_series.sort_values('sales'),end='\n\n')
print(sales_series.sort_values('sales',ascending=False))

         index  sales
0       coffee     10
1       coffee     20
2        sugar     30
3         milk     40
4        water     50
5  milk_powder     60

         index  sales
5  milk_powder     60
4        water     50
3         milk     40
2        sugar     30
1       coffee     20
0       coffee     10


In [18]:
#arithmetic ops using functions --> add(), mul(), div(), pow(), sub(), floordiv(), mod()
print(sales_series.loc[:,'sales'].add(2))
print(sales_series.loc[:,'sales'].mul(2))
print(sales_series.loc[:,'sales'].sub(2))
print(sales_series.loc[:,'sales'].div(2))
print(sales_series.loc[:,'sales'].floordiv(3)) #gives Quotient
print(sales_series.loc[:,'sales'].pow(2))
print(sales_series.loc[:,'sales'].mod(3))

0    12
1    22
2    32
3    42
4    52
5    62
Name: sales, dtype: int64
0     20
1     40
2     60
3     80
4    100
5    120
Name: sales, dtype: int64
0     8
1    18
2    28
3    38
4    48
5    58
Name: sales, dtype: int64
0     5.0
1    10.0
2    15.0
3    20.0
4    25.0
5    30.0
Name: sales, dtype: float64
0     3
1     6
2    10
3    13
4    16
5    20
Name: sales, dtype: int64
0     100
1     400
2     900
3    1600
4    2500
5    3600
Name: sales, dtype: int64
0    1
1    2
2    0
3    1
4    2
5    0
Name: sales, dtype: int64


In [49]:
#String methods

#concatenation
sales_series2 = '$'+((sales_series.loc[:,'sales'].astype('float')).astype('str'))
print(sales_series2)

#removing trailing , left, right spaces --> strip(), lstrip(), rstrip()
print(sales_series2.str.strip())

#Upper, Lower cases
print(sales_series2.str.upper())
print(sales_series2.str.lower())

#Finding string
print(sales_series2.str.contains('$200.0'))

0    $10.0
1    $20.0
2    $30.0
3    $40.0
4    $50.0
5    $60.0
Name: sales, dtype: object
0    $10.0
1    $20.0
2    $30.0
3    $40.0
4    $50.0
5    $60.0
Name: sales, dtype: object
0    $10.0
1    $20.0
2    $30.0
3    $40.0
4    $50.0
5    $60.0
Name: sales, dtype: object
0    $10.0
1    $20.0
2    $30.0
3    $40.0
4    $50.0
5    $60.0
Name: sales, dtype: object
0    False
1    False
2    False
3    False
4    False
5    False
Name: sales, dtype: bool


In [72]:
#Aggregation methods -->count(),first(),last(),mean(),median(),min(),max(),argmax(),argmin(),std(),var(),mod,prod(),sum(),quantile()
#print(sales_series.groupby('sales').count())
print(sales_series['sales'].value_counts())
print(sales_series['sales'].sum())
print(sales_series['sales'].mean())
print(sales_series['sales'].median())
print(sales_series['sales'].argmax())
print(sales_series['sales'].argmin())
print(sales_series['sales'].argmax())
print(sales_series['sales'].prod())
print(sales_series['sales'].quantile([0.25]))

sales
10    1
20    1
30    1
40    1
50    1
60    1
Name: count, dtype: int64
210
35.0
35.0
5
0
5
720000000
0.25    22.5
Name: sales, dtype: float64


In [8]:
# NULL values
series = pd.Series([10,20,30,np.nan,40,np.nan,50],name='col1') #Null values using np.nan --> it's a float value under the hood, which helps in case of vectorization
print(series,end='\n\n')

series = pd.Series([10,20,30,pd.NA,40,pd.NA,50], name='col1') #Null values using pd.NA --> it's a integer value under the hood, which helps in case of vectorization
print(series)

0    10.0
1    20.0
2    30.0
3     NaN
4    40.0
5     NaN
6    50.0
Name: col1, dtype: float64

0      10
1      20
2      30
3    <NA>
4      40
5    <NA>
6      50
Name: col1, dtype: object


In [12]:
#Finding Missing/NA/null data

print(series.isna(),end='\n\n') # returns list for each index whether data is NA
print(series.isna().sum(),end='\n\n') #--> returns total number of NA values
print(series.value_counts(dropna=False)) #--> Returns list of all unique values with their frequencies


0    False
1    False
2    False
3     True
4    False
5     True
6    False
Name: col1, dtype: bool

2

col1
<NA>    2
10      1
20      1
30      1
40      1
50      1
Name: count, dtype: int64


In [17]:
#Handling missing data --> There are only 2 ways EITHER DELETE(DROP) DATA OR FILL NA DATA with some other data
#.dropna(), .fillna()

series1 = series.copy()
print(series1,end='\n\n')

#Drop rows which have na values
series1.dropna(inplace=True)
print(series1, end='\n\n')

#Fill NA data with some another value
series2 = series.copy()
series2.fillna(0,inplace=True)
print(series2)

0      10
1      20
2      30
3    <NA>
4      40
5    <NA>
6      50
Name: col1, dtype: object

0    10
1    20
2    30
4    40
6    50
Name: col1, dtype: object

0    10
1    20
2    30
3     0
4    40
5     0
6    50
Name: col1, dtype: int64


C:\Users\adity\AppData\Local\Temp\ipykernel_13948\1563319486.py:13: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  series2.fillna(0,inplace=True)


In [23]:
#.apply() function --> this allows us to use our custom functions on series

#function for giving 10% discount on every product
def fn(price):
    price = price - (price*0.1)
    return price

series3 = series.copy()
print(series3.apply(fn))

0     9.0
1    18.0
2    27.0
3    <NA>
4    36.0
5    <NA>
6    45.0
Name: col1, dtype: object


In [3]:
#DataFrames--> It is equivalent to excel spreadsheet, sql table, collection of multiple pd.Series(columns)

data = {
    'item':['coffee','tea','sugar','water','milk'],
    'sales':[10,20,30,40,50]
}

df = pd.DataFrame(data)
print(df)

     item  sales
0  coffee     10
1     tea     20
2   sugar     30
3   water     40
4    milk     50


In [36]:
df

item  sales
0  coffee     10
1     tea     20
2   sugar     30
3   water     40
4    milk     50

In [37]:
#Properties of dataframe --> shape, columns, index, axes,dtype

print(df.shape)
print(df.columns)
print(df.index)
print(df.axes)
print(df.dtypes)

(5, 2)
Index(['item', 'sales'], dtype='object')
RangeIndex(start=0, stop=5, step=1)
[RangeIndex(start=0, stop=5, step=1), Index(['item', 'sales'], dtype='object')]
item     object
sales     int64
dtype: object


In [39]:
df.rename(columns={'sales':'sales_amt'},inplace=True)

In [44]:
#Exploring dataframe--> .head(), .tail(), .sample(), .info(), .describe()
print(df.head(3), end='\n\n')
print(df.tail(3), end='\n\n')
print(df.sample(), end='\n\n')
print(df.info(), end='\n\n')
print(df.describe(), end='\n\n')

     item  sales_amt
0  coffee         10
1     tea         20
2   sugar         30

    item  sales_amt
2  sugar         30
3  water         40
4   milk         50

    item  sales_amt
3  water         40

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   item       5 non-null      object
 1   sales_amt  5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes
None

       sales_amt
count   5.000000
mean   30.000000
std    15.811388
min    10.000000
25%    20.000000
50%    30.000000
75%    40.000000
max    50.000000



In [46]:
df.describe(include="all") #detailed description of all columns statistical analysis

item  sales_amt
count        5   5.000000
unique       5        NaN
top     coffee        NaN
freq         1        NaN
mean       NaN  30.000000
std        NaN  15.811388
min        NaN  10.000000
25%        NaN  20.000000
50%        NaN  30.000000
75%        NaN  40.000000
max        NaN  50.000000

In [49]:
#Access columns all data (Series) --> there are 2 ways either df['col name'] or df.'col name'

meth1 = df['sales_amt']
print(meth1)
print('\n')
meth2 = df.sales_amt
print(meth2)

0    10
1    20
2    30
3    40
4    50
Name: sales_amt, dtype: int64


0    10
1    20
2    30
3    40
4    50
Name: sales_amt, dtype: int64


In [5]:
#Apply inbuilt aggregation/mathematical function of columns of dataframe
print(df['sales'].mean())
print(df['sales'].nunique()) #give number of unique elements in column
print(df['sales'].sum())
print(df['sales'].unique()) # returns list of all unique elements

30.0
5
150
[10 20 30 40 50]


In [8]:
#Multi selection of rows by column name
print(df[['sales','item']])

   sales    item
0     10  coffee
1     20     tea
2     30   sugar
3     40   water
4     50    milk


In [11]:
#multi selection of columns & rows with .iloc[]
print(df.iloc[:,0:]) #all rows and 0(first) to last index of column
print(df.iloc[0:3,:]) # all columns and 0,1,2 index of rows

     item  sales
0  coffee     10
1     tea     20
2   sugar     30
3   water     40
4    milk     50
     item  sales
0  coffee     10
1     tea     20
2   sugar     30


In [15]:
#multiselection of columns with .loc[]
print(df.loc[:,'item':'sales']) # all rows and columns from items to sales (left to right order for columns)

     item  sales
0  coffee     10
1     tea     20
2   sugar     30
3   water     40
4    milk     50


In [27]:
#dropping data, data can be dropped in 2 ways row or col fashion
# we can drop data using .drop() function, axis=0 to drop rows, axis=1 to drop cols

#drop column
print(df.drop('item',axis=1),end='\n\n')

#drop rows
print(df.drop([0], axis=0),end='\n\n') #dropping single row
print(df.drop([0,1,2],axis=0), end='\n\n') #dropping multiple rows (at index 0 1 2)

   sales
0     10
1     20
2     30
3     40
4     50

    item  sales
1    tea     20
2  sugar     30
3  water     40
4   milk     50

    item  sales
3  water     40
4   milk     50



In [35]:
#drop duplicates
df1=df.copy()
print(df1.drop_duplicates(subset='item',keep="first",ignore_index=True))

     item  sales
0  coffee     10
1     tea     20
2   sugar     30
3   water     40
4    milk     50


In [37]:
#Identifying missing data --> 2 ways --> df.isna().sum() and df.info() methods

print(df.isna().sum(), end='\n\n')
print(df.info())

item     0
sales    0
dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   item    5 non-null      object
 1   sales   5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes
None


In [3]:
#fill missing data --> df.fillna() method

dictdfna = {
    'col1':[pd.NA,10,20,30,40,pd.NA],
    'col2':['yo','yo1',pd.NA,'yo2',pd.NA,pd.NA]
}

dfna = pd.DataFrame(dictdfna)
print(dfna,end='\n\n')

print(dfna.fillna(0), end="\n\n") #fill 0 in entire dataframe where NA is present
print(dfna.fillna({'col1':0})) #fill 0 wherever NA is present only in SPECIFIC COLUMN

   col1  col2
0  <NA>    yo
1    10   yo1
2    20  <NA>
3    30   yo2
4    40  <NA>
5  <NA>  <NA>

   col1 col2
0     0   yo
1    10  yo1
2    20    0
3    30  yo2
4    40    0
5     0    0

   col1  col2
0     0    yo
1    10   yo1
2    20  <NA>
3    30   yo2
4    40  <NA>
5     0  <NA>


C:\Users\adity\AppData\Local\Temp\ipykernel_13696\3599555472.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  print(dfna.fillna(0), end="\n\n") #fill 0 in entire dataframe where NA is present
C:\Users\adity\AppData\Local\Temp\ipykernel_13696\3599555472.py:12: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  print(dfna.fillna({'col1':0})) #fill 0 wherever NA is present only in SPECIFIC COLUMN


In [4]:
#droppping NA values rows --> .dropna()
print(dfna.dropna(), end='\n\n') # Drop all the rows in entire DF wherever NA is present even in single column
print(dfna.dropna(subset=['col1'])) # Drop all rows wherever NA is present in SPECIFIC COLUMN(S)

  col1 col2
1   10  yo1
3   30  yo2

  col1  col2
1   10   yo1
2   20  <NA>
3   30   yo2
4   40  <NA>


In [15]:
#Filtering data using .loc[] command and printing all rows
print(dfna.loc[dfna['col2']=='yo1'],end='\n\n') #all columns & rows where rows in col2 == 'yo1'
print((dfna.loc[dfna['col2']=='yo1']).loc[:,'col1']) #all rows where col2=='yo1' but only column specific column(col1) displayed
#OR
print('\n')
print(dfna.loc[dfna['col2']=='yo1', ["col1"]])
print('\n')

#For multiple conditions check
condition = (dfna['col1']==10) & (dfna['col2']=='yo1')
print(dfna.loc[condition])

  col1 col2
1   10  yo1

1    10
Name: col1, dtype: object


  col1
1   10


  col1 col2
1   10  yo1


In [16]:
#Query df using df.query()
print(dfna.query(" col1 in [10] and col2 in 'yo1' "))

  col1 col2
1   10  yo1


In [3]:
#Sorting data frame by index

##create dataframe on custom index
data = [
    [10,20,30,40],
    ['yo1','yo2','yo3','yo4'],
    [5,6,2,1]
]
custom_index = ['coffee','sugar','milk']
df = pd.DataFrame(data, index=custom_index, columns=['col3','col1','col4','col2'])
print(df, end='\n\n')

#Sort df by custom index (axis=0)
print(df.sort_index(axis=0), end='\n\n')

#sort df by columns index(names) (axis=1)
print(df.sort_index(axis=1))

       col3 col1 col4 col2
coffee   10   20   30   40
sugar   yo1  yo2  yo3  yo4
milk      5    6    2    1

       col3 col1 col4 col2
coffee   10   20   30   40
milk      5    6    2    1
sugar   yo1  yo2  yo3  yo4

       col1 col2 col3 col4
coffee   20   40   10   30
sugar   yo2  yo4  yo1  yo3
milk      6    1    5    2


In [4]:
#Change the order of column of df--> df.reindex()

print(df.reindex(labels=['col1','col2','col4','col3'],axis=1))

       col1 col2 col4 col3
coffee   20   40   30   10
sugar   yo2  yo4  yo3  yo1
milk      6    1    2    5


In [5]:
#Create new column --> just give new name inside df[] for eg df['new col'] = df['old_col']*2
df1 = df.copy()
df1['newcol1'] = (df1['col3'].astype('str'))+'5'
print(df1)

       col3 col1 col4 col2 newcol1
coffee   10   20   30   40     105
sugar   yo1  yo2  yo3  yo4    yo15
milk      5    6    2    1      55


In [6]:
#Column creation using np.select()
conditions=[
    (df['col3'] == 'yo1'),
    (df['col3'] == 10),
    (df['col3'] == 5)
]
choices = ['large','ok','small']

df1['newColWithChoice'] = np.select(conditions, choices, default='dontknow')
print(df1)

       col3 col1 col4 col2 newcol1 newColWithChoice
coffee   10   20   30   40     105               ok
sugar   yo1  yo2  yo3  yo4    yo15            large
milk      5    6    2    1      55            small


In [7]:
#Create multiple columns using .assign() method
print(df1.assign(newcol2=(((df1["col2"].astype('str')))+'@!#'), newcol3=(((df1["col1"].astype('str')))+'123%^&')))

       col3 col1 col4 col2 newcol1 newColWithChoice newcol2    newcol3
coffee   10   20   30   40     105               ok   40@!#   20123%^&
sugar   yo1  yo2  yo3  yo4    yo15            large  yo4@!#  yo2123%^&
milk      5    6    2    1      55            small    1@!#    6123%^&


In [8]:
#Get detail info of memory usage --> Important for large data sets
print(df1.info(memory_usage="deep"), end='\n\n')
print(df1.memory_usage(deep=True), end='\n\n')
print(str(df1.memory_usage(deep=True).sum()) + 'bytes')

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, coffee to milk
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   col3              3 non-null      object
 1   col1              3 non-null      object
 2   col4              3 non-null      object
 3   col2              3 non-null      object
 4   newcol1           3 non-null      object
 5   newColWithChoice  3 non-null      object
dtypes: object(6)
memory usage: 1.2 KB
None

Index               294
col3                132
col1                132
col4                132
col2                132
newcol1             180
newColWithChoice    183
dtype: int64

1185bytes


In [9]:
#group by function --> df.groupby(some col name)
print(df1.groupby('col1')['col2'].sum(),end='\n\n')
print(df1.groupby('col1').sum())

col1
6        1
20      40
yo2    yo4
Name: col2, dtype: object

     col3 col4 col2 newcol1 newColWithChoice
col1                                        
6       5    2    1      55            small
20     10   30   40     105               ok
yo2   yo1  yo3  yo4    yo15            large


In [42]:
#aggregation function with groupby --> df.groupby(some col).agg(some aggreagtion measure like SUM)

data = {
    'products':['coffee','bread','coffee','water','water'],
    'weights':[2,4,8,1,6],
    'price':[10,20,50,90,60],
    'units':[20,40,30,2,7],
    'brand':['yo1','yo4','yo2','yo3','yo5']
}

df = pd.DataFrame(data)
print(df, end='\n\n')

#groupby + aggregation
print(df.groupby(['products']).agg('sum'), end='\n\n') #groupby will be applied on products and willbe aggregated using (sum) for all cols
print(df.groupby(['products']).agg('sum')['weights']) # will represent total weights taken by each category of product
print('\n')
print(df.groupby(['products']).agg({'weights':['sum']})) # will represent total weights taken by each category of product


  products  weights  price  units brand
0   coffee        2     10     20   yo1
1    bread        4     20     40   yo4
2   coffee        8     50     30   yo2
3    water        1     90      2   yo3
4    water        6     60      7   yo5

          weights  price  units   brand
products                               
bread           4     20     40     yo4
coffee         10     60     50  yo1yo2
water           7    150      9  yo3yo5

products
bread      4
coffee    10
water      7
Name: weights, dtype: int64


         weights
             sum
products        
bread          4
coffee        10
water          7


In [43]:
#groupby and MULTIPLE AGGREGATION on multiple columns
print(df.groupby(['products']).agg({'weights':['sum','mean'],'units':['min','max']}))

         weights      units    
             sum mean   min max
products                       
bread          4  4.0    40  40
coffee        10  5.0    20  30
water          7  3.5     2   7


In [44]:
#Working with datetime

from datetime import datetime
now = datetime.now()
print(now)
print(str(now)[0:10])

2024-08-09 13:19:11.846711
2024-08-09


In [47]:
#Adding Datetime column using a numpy array then typecasting it into datetime64[ns]
df1 = df.copy()
df1['date'] = np.array(['2024-08-09','2017-04-23','2016-09-15','2021-10-29','2020-09-12'])
df1['date'].astype('datetime64[ns]')
print(df1)

  products  weights  price  units brand        date
0   coffee        2     10     20   yo1  2024-08-09
1    bread        4     20     40   yo4  2017-04-23
2   coffee        8     50     30   yo2  2016-09-15
3    water        1     90      2   yo3  2021-10-29
4    water        6     60      7   yo5  2020-09-12


In [51]:
#Adding Datetime column using numpyarray & pd.toDateTime() method
df2 = df1.copy()
l1 = np.array(['2024-08-09','2017-04-23','2016-09-15','2021-10-29','2020-09-12'])
df2['date2'] = pd.to_datetime(l1,format="%Y-%m-%d",errors="coerce")#we're using np.array to put data in col then defining format
print(df2)

  products  weights  price  units brand        date      date2
0   coffee        2     10     20   yo1  2024-08-09 2024-08-09
1    bread        4     20     40   yo4  2017-04-23 2017-04-23
2   coffee        8     50     30   yo2  2016-09-15 2016-09-15
3    water        1     90      2   yo3  2021-10-29 2021-10-29
4    water        6     60      7   yo5  2020-09-12 2020-09-12


In [52]:
#Convert datetime column to string
df2['date_str'] = df2['date2'].astype('str')
print(df2)

  products  weights  price  units brand        date      date2    date_str
0   coffee        2     10     20   yo1  2024-08-09 2024-08-09  2024-08-09
1    bread        4     20     40   yo4  2017-04-23 2017-04-23  2017-04-23
2   coffee        8     50     30   yo2  2016-09-15 2016-09-15  2016-09-15
3    water        1     90      2   yo3  2021-10-29 2021-10-29  2021-10-29
4    water        6     60      7   yo5  2020-09-12 2020-09-12  2020-09-12


In [59]:
#extract different features of datetime like(month name, day name etc) column to string using dt.strftime() function
df2 = df2.assign(date3=df2['date2'].dt.strftime("%Y-%B-%a"))
print(df2)

  products  weights  price  units brand        date      date2    date_str  \
0   coffee        2     10     20   yo1  2024-08-09 2024-08-09  2024-08-09   
1    bread        4     20     40   yo4  2017-04-23 2017-04-23  2017-04-23   
2   coffee        8     50     30   yo2  2016-09-15 2016-09-15  2016-09-15   
3    water        1     90      2   yo3  2021-10-29 2021-10-29  2021-10-29   
4    water        6     60      7   yo5  2020-09-12 2020-09-12  2020-09-12   

                date3  
0     2024-August-Fri  
1      2017-April-Sun  
2  2016-September-Thu  
3    2021-October-Fri  
4  2020-September-Sat  


In [66]:
#Extract DataTime components from datatime columns
print(df2['date2'].dt.year)
print(df2['date2'].dt.dayofweek)
print(df2['date2'].dt.month)
print(df2['date2'].dt.day)

0    2024
1    2017
2    2016
3    2021
4    2020
Name: date2, dtype: int32
0    4
1    6
2    3
3    4
4    5
Name: date2, dtype: int32
0     8
1     4
2     9
3    10
4     9
Name: date2, dtype: int32
0     9
1    23
2    15
3    29
4    12
Name: date2, dtype: int32


In [71]:
#Concate 2 dataframes
print(df2, end='\n\n')
print(df1, end='\n\n')
print(pd.concat([df2,df1]))

  products  weights  price  units brand        date      date2    date_str  \
0   coffee        2     10     20   yo1  2024-08-09 2024-08-09  2024-08-09   
1    bread        4     20     40   yo4  2017-04-23 2017-04-23  2017-04-23   
2   coffee        8     50     30   yo2  2016-09-15 2016-09-15  2016-09-15   
3    water        1     90      2   yo3  2021-10-29 2021-10-29  2021-10-29   
4    water        6     60      7   yo5  2020-09-12 2020-09-12  2020-09-12   

                date3  
0     2024-August-Fri  
1      2017-April-Sun  
2  2016-September-Thu  
3    2021-October-Fri  
4  2020-September-Sat  

  products  weights  price  units brand        date
0   coffee        2     10     20   yo1  2024-08-09
1    bread        4     20     40   yo4  2017-04-23
2   coffee        8     50     30   yo2  2016-09-15
3    water        1     90      2   yo3  2021-10-29
4    water        6     60      7   yo5  2020-09-12

  products  weights  price  units brand        date      date2    date_st